### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by NeilJohnson0930** [Josh-Yi/FFT-3D-Demo#1]
您好Josh前辈，我想做一个时间序列图像的3d dft处理，但是不知道具体怎么操作，您的代码我有些地方看不懂，请问方便添加您的联系方式详细沟通一下吗

**Comment by Josh-Yi** [comment]
朋友你好，我们可以直接在这个issue下面沟通。

**Comment by Josh-Yi** [comment]
> 

朋友你好，我们可以直接在这个issue下面沟通。

**Comment by NeilJohnson0930** [comment]
好的前辈，您的代码我没有“from plt3d_ import MATSHOW_3D_abs as ms”这一部分，不能成功load图片导致代码不能运行，对后面的理解有些影响。我这边是经过模拟产生一段时间下的若干张图片A(x,y,t)，想要在x,y,t三个维度做三维傅里叶变换。之前学习了一维二维的傅里叶变换，二维的变换是可以直接以一张图片作为输入进行变换，我想知道三维的时候可以用若干张图像作为输入去做这个变换吗？（我看您的代码好像可以这样？）如果是用参数去输入，可能是因为对这方面基础掌握不牢固，我快被搞晕了，网上几乎找不到更多三维变换的参考资料，所以想跟前辈请教让您给我解答一下。万望勿辞~

**Comment by NeilJohnson0930** [comment]
前辈，您的IMG.shape打印出来是(21135, 40, 32, 32)，这应该是进行三维变换的关键，为什么您这个是四位数呢？（三维不应该是三位数吗？我这边的img.shape打印出来是(240, 320)，是单张图像二维的情况）我卡在这里了，不知道怎么把多张照片和时间元素加入进来。

**Comment by Josh-Yi** [comment]
> 前辈，您的IMG.shape打印出来是(21135, 40, 32, 32)，这应该是进行三维变换的关键，为什么您这个是四位数呢？（三维不应该是三位数吗？我这边的img.shape打印出来是(240, 320)，是单张图像二维的情况）我卡在这里了，不知道怎么把多张照片和时间元素加入进来。

你好朋友

(21135, 40, 32, 32)是一个有21135个图像的3D图像数据集，做变换的时候只对一个 (40, 32, 32) 体素块做变换。

这个数据集很快就会公开，我随后会把它加入到这个repository。

如果朋友你是想做视频分类任务，是可以在三个维度（frames, l,w）上做变换的 （要把图片在时间维度上叠起来）。我也很好奇三个维傅里叶变换后可不可以提取出时间轴的更多信息。

朋友加油，希望能帮到你：）

**Comment by NeilJohnson0930** [comment]
前辈，太棒了，期待你的数据更新。我做的不是视频分类，是要对时间维度上叠起来多张图片进行傅里叶变换。还是希望可以和你详细沟通实现部分，我感觉你这个已经很接近了。

**Comment by Josh-Yi** [comment]
> 前辈，太棒了，期待你的数据更新。我做的不是视频分类，是要对时间维度上叠起来多张图片进行傅里叶变换。还是希望可以和你详细沟通实现部分，我感觉你这个已经很接近了。

你好，没有问题的。容我好奇一下，你想同时对时间维度傅里叶变换的初衷是什么啊？

**Comment by NeilJohnson0930** [comment]
将一个时间序列里的图像经过三位傅里叶变换得到一个能量分布谱的信息。我想给您attach一个论文，但是不知道怎么操作，您方便留一个联系方式吗？

**Comment by Josh-Yi** [comment]
你好，这是我的邮箱：zhiwangshishenme@outlook.com
